on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Debug Directory Structure
        run: |
          echo "Workspace is: ${{ github.workspace }}"
          ls -R ${{ github.workspace }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Ensure build directory exists
        run: mkdir -p ${{ github.workspace }}/build

      - name: Install ADF Utilities package
        run: npm install
        working-directory: ${{ github.workspace }}/build

      - name: Validate
        run: npm run build validate ${{ github.workspace }} /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/${{ secrets.DF_RESOURCE_GROUP }}/providers/Microsoft.DataFactory/factories/${{ secrets.ADF_NAME }} ${{ github.workspace }}/publish_config.json
        working-directory: ${{ github.workspace }}/build

      - name: Validate and Generate ARM template
        run: npm run build export ${{ github.workspace }} /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/${{ secrets.DF_RESOURCE_GROUP }}/providers/Microsoft.DataFactory/factories/${{ secrets.ADF_NAME }} "ExportedArmTemplate" ${{ github.workspace }}/publish_config.json
        working-directory: ${{ github.workspace }}/build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ExportedArmTemplate
